Gpu chunk fix
scipion-em/scipion-pyworkflow pull request #203
Opened 2021-01-22 16:24 UTC by pconesa

This fixes an issue reported by email, where user was setting several items in the GPUs and several mpis.

````
Traceback (most recent call last):
  File "/usr/local/apps/scipion/3.0.6/anaconda/envs/.scipion3env/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_mpirun.py", line 54, in <module>
    runProtocolMainMPI(projectPath, dbPath, protId, comm)
  File "/usr/local/apps/scipion/3.0.6/anaconda/envs/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 2229, in runProtocolMainMPI
    executor = MPIStepExecutor(hostConfig, protocol.numberOfMpi.get() - 1,
  File "/usr/local/apps/scipion/3.0.6/anaconda/envs/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 342, in __init__
    ThreadStepExecutor.__init__(self, hostConfig, nMPI, **kwargs)
  File "/usr/local/apps/scipion/3.0.6/anaconda/envs/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 177, in __init__
    self.gpuDict[node] = list(self.gpuList[i*chunk:(i+1)*chunk])
TypeError: slice indices must be integers or None or have an __index__ method 

````

chunk reaches that point being a decimal number and not integer. Probably we missed this when migrating to python3.

I've tested this change in a 2 GPU machine and worked.

2021-01-22 16:43 UTC, fonsecareyna82 approved these changes

2021-01-23 15:42 UTC, azazellochg requested changes
There are more problems with this. I'm investigating

2021-01-23 15:49 UTC, azazellochg commented
using numpy arrays is causing problems. Here is fixed code:
```
import numpy as np

def test(nThreads, gpus):
    gpuDict = {}
    gpuList = gpus
    
    if gpuList:
        nodes = range(nThreads)
        nGpu = len(gpuList)
    
        if nGpu > nThreads:
            chunk = int(nGpu / nThreads)
            for i, node in enumerate(nodes):
                gpuDict[node] = list(gpuList[i*chunk:(i+1)*chunk])
        else:
            # Expand gpuList repeating until reach nThreads items
            if nThreads > nGpu:
                #newList = np.asarray(gpuList) * (int(nThreads/nGpu)+1)
                newList = gpuList * (int(nThreads/nGpu)+1)
                #print(newList)
                gpuList = newList[:nThreads]
    
            for node, gpu in zip(nodes, gpuList):
                gpuDict[node] = [gpu]
        
    print("input nThr=", nThreads, "\ninput GPU ids=", gpus, "\noutput threads {thr:gpus}:", gpuDict, "\n")


test(2,[0,1,2,3])
test(4,[0,1])
test(4,[0,1,2,3])
test(1,[0,1,2])
test(3,[0,1,2,3])
test(4,[0,1,2])

```
Which prints:
```
input nThr= 2 
input GPU ids= [0, 1, 2, 3] 
output threads {thr:gpus}: {0: [0, 1], 1: [2, 3]} 

input nThr= 4 
input GPU ids= [0, 1] 
output threads {thr:gpus}: {0: [0], 1: [1], 2: [0], 3: [1]} 

input nThr= 4 
input GPU ids= [0, 1, 2, 3] 
output threads {thr:gpus}: {0: [0], 1: [1], 2: [2], 3: [3]} 

input nThr= 1 
input GPU ids= [0, 1, 2] 
output threads {thr:gpus}: {0: [0, 1, 2]} 

input nThr= 3 
input GPU ids= [0, 1, 2, 3] 
output threads {thr:gpus}: {0: [0], 1: [1], 2: [2]} 

input nThr= 4 
input GPU ids= [0, 1, 2] 
output threads {thr:gpus}: {0: [0], 1: [1], 2: [2], 3: [0]}
```

My only concern is when using 4 threads and 3 gpus, the fourth thread is not used

2021-01-23 16:05 UTC, azazellochg approved these changes

2021-01-25 08:00 UTC, pconesa commented
Good you caught the numpy case!!

2021-02-01 09:44 UTC, merged